add_newline = false

format = """
$python\
[W1.](bold fg:#207dab)\
$username\
$git_branch$git_commit\
$directory[>](#2abfb0 bold) \
"""
#format = """$character"""
#296685

right_format = """$time"""

[line_break]
disabled = true 

[python]
##symbol = "ğŸ‘¾ "
#format = "[${symbol}${version}\\($virtualenv\\)]($style) "
format = "[\\($virtualenv\\)]($style) "
version_format = "${raw}"
symbol = "ğŸ"

[directory]
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "â€¦/"
home_symbol = "~"
format = " [$path]($style)[$read_only]($read_only_style)"

[git_branch]
#format = "[ $symbol$branch ](fg:#222222 bg:#8ab028)"
#format = "[ $symbol$branch ](fg:#222222 bg:#216c70)"
#format = "[ $symbol$branch ](fg:#222222 bg:#8f3928)"
format = "[ $symbol$branch ](fg:#222222 bg:#9c341f)"
only_attached = true
symbol = "î‚  "
#9c341f
#8f3928
#15474a

[git_commit]
commit_hash_length = 8
#tag_symbol = "ğŸ”–"
#format = " [ $hash$tag ](fg:#333333 bold bg:#ab513f)"
format = "[ $hash$tag ](fg:#333333 bold bg:#74358f)"
#15474a

[username]
style_user = "bold"
style_root = "white bold"
#format = "[$user](#666666 italic)"
format = "[$user](#666666)"
disabled = false
show_always = true

[time]
disabled = false
#format = '[ğŸ•™$time](#555555) '
format = '[$time](#555555) '
